import type { IReportsRepository, PaginationOpts, PaginatedResult } from "../interfaces";
import type {
  Report,
  ReportType,
  ReportStatus,
  StatusHistoryEntry,
  FeedbackEntry,
} from "@/types/api";
import { getStore } from "./store";
import { getLLM, completeJSON } from "@/lib/llm";
import { buildReportPrompt } from "@/lib/llm/prompts";

type ReportLLMOutput = {
  title: { en: string; zh: string };
  markdown: { en: string; zh: string };
};

export class MockReportsRepository implements IReportsRepository {
  async list(
    opts?: PaginationOpts & { status?: ReportStatus; type?: ReportType }
  ): Promise<PaginatedResult<Omit<Report, "markdown">>> {
    const store = getStore();
    const page = opts?.page ?? 1;
    const pageSize = opts?.pageSize ?? 20;
    let items: Omit<Report, "markdown">[] = Array.from(store.reports.values())
      .sort((a, b) => b.date.localeCompare(a.date))
      .map(({ markdown: _md, ...rest }) => rest);
    if (opts?.status) items = items.filter((r) => r.status === opts.status);
    if (opts?.type) items = items.filter((r) => r.type === opts.type);
    const total = items.length;
    const start = (page - 1) * pageSize;
    return {
      items: items.slice(start, start + pageSize),
      total,
      page,
      pageSize,
    };
  }

  async getById(id: string): Promise<Report | null> {
    return getStore().reports.get(id) ?? null;
  }

  async create(data: {
    diagnosisId: string;
    type: ReportType;
    audience: string;
  }): Promise<Report> {
    const store = getStore();
    const id = store.nextId("r");
    const now = store.now();

    // Create report in draft state
    const report: Report = {
      id,
      title: { en: "Generating report...", zh: "报告生成中..." },
      type: data.type,
      status: "in_progress",
      ownerKey: "ops_lead",
      currentVersion: 1,
      date: store.today(),
      sourceDiagnosisId: data.diagnosisId,
      markdown: { en: "", zh: "" },
      statusHistory: [
        { from: "draft" as ReportStatus, to: "in_progress", changedBy: "system", changedAt: now },
      ],
      versions: [
        {
          version: 1,
          createdAt: now,
          createdBy: "system",
          note: { en: "Auto-generated by AI", zh: "AI自动生成" },
          isCurrent: true,
        },
      ],
      feedback: [],
    };

    store.reports.set(id, report);

    // Run LLM in background
    this.generateReportLLM(id, data).catch((err) => {
      console.error(`[Reports] LLM failed for ${id}:`, err);
      const r = store.reports.get(id);
      if (r) {
        r.status = "draft";
        r.title = { en: "Generation Failed", zh: "生成失败" };
        r.markdown = {
          en: `Report generation failed: ${err.message}`,
          zh: `报告生成失败: ${err.message}`,
        };
      }
    });

    return report;
  }

  async updateStatus(
    id: string,
    data: { status: ReportStatus; currentStatus?: string; note?: string }
  ): Promise<StatusHistoryEntry> {
    const store = getStore();
    const report = store.reports.get(id);
    const now = store.now();

    const entry: StatusHistoryEntry = {
      from: (data.currentStatus ?? report?.status ?? "unknown") as ReportStatus,
      to: data.status,
      changedBy: "ops_lead",
      changedAt: now,
      note: data.note,
    };

    if (report) {
      report.status = data.status;
      report.statusHistory.push(entry);
    }

    return entry;
  }

  async addFeedback(
    id: string,
    data: { score: number; comment: string }
  ): Promise<FeedbackEntry> {
    const store = getStore();
    const report = store.reports.get(id);
    const now = store.now();

    const entry: FeedbackEntry = {
      id: store.nextId("f"),
      score: data.score as 1 | 2 | 3 | 4 | 5,
      comment: { en: data.comment, zh: data.comment },
      by: "ops_lead",
      createdAt: now,
    };

    if (report) {
      report.feedback.push(entry);
    }

    return entry;
  }

  private async generateReportLLM(
    id: string,
    data: { diagnosisId: string; type: ReportType; audience: string }
  ): Promise<void> {
    const store = getStore();
    const llm = getLLM();

    // Get source diagnosis for context
    const diagnosis = store.diagnoses.get(data.diagnosisId);
    const diagnosisSummary = diagnosis
      ? `Type: ${diagnosis.type}
Time Range: ${diagnosis.timeRange}
Summary: ${diagnosis.summary.en}
Anomalies: ${diagnosis.anomalies.map((a) => `${a.metric} (${a.scope.en}): ${a.changePercent}%`).join("; ")}
Hypotheses: ${diagnosis.hypotheses.map((h) => `${h.title.en} (confidence: ${h.confidence})`).join("; ")}
Recommendations: ${diagnosis.recommendations.map((r) => `[${r.priority}] ${r.title.en}`).join("; ")}`
      : "No diagnosis data available. Generate a general operating report based on enterprise context.";

    const messages = buildReportPrompt({
      diagnosisSummary,
      reportType: data.type,
      audience: data.audience,
      enterprise: store.enterprise,
    });

    const result = await completeJSON<ReportLLMOutput>(llm, messages, {
      temperature: 0.6,
      maxTokens: 4096,
    });

    // Update report with generated content
    const report = store.reports.get(id);
    if (!report) return;

    report.title = result.title;
    report.markdown = result.markdown;
    report.status = "draft";
    report.statusHistory.push({
      from: "in_progress",
      to: "draft",
      changedBy: "system",
      changedAt: store.now(),
      note: "Generation complete",
    });
  }
}
