import type { DataSource, ImportRecord, FieldMapping } from "@/types/api";
import { bi } from "./helpers";

export const mockDataSources: DataSource[] = [
  {
    id: "ds1",
    name: bi("Tmall Trade Data", "天猫交易数据"),
    type: "api",
    channel: "tmall",
    lastSync: "2025-03-09 06:00",
    recordCount: 184200,
    status: "active",
  },
  {
    id: "ds2",
    name: bi("Douyin E-commerce Data", "抖音电商数据"),
    type: "api",
    channel: "douyin",
    lastSync: "2025-03-09 06:00",
    recordCount: 126500,
    status: "active",
  },
  {
    id: "ds3",
    name: bi("Xiaohongshu Content Metrics", "小红书内容数据"),
    type: "api",
    channel: "xiaohongshu",
    lastSync: "2025-03-09 06:00",
    recordCount: 45800,
    status: "active",
  },
  {
    id: "ds4",
    name: bi("JD Sales Export", "京东销售导出"),
    type: "csv",
    channel: "jd",
    lastSync: "2025-03-08 22:00",
    recordCount: 38200,
    status: "active",
  },
  {
    id: "ds5",
    name: bi("Pinduoduo Order Data", "拼多多订单数据"),
    type: "csv",
    channel: "pinduoduo",
    lastSync: "2025-03-08 18:00",
    recordCount: 15600,
    status: "active",
  },
  {
    id: "ds6",
    name: bi("Ad Spend Tracker (All Channels)", "广告投放追踪（全渠道）"),
    type: "excel",
    channel: "all",
    lastSync: "2025-03-09 08:00",
    recordCount: 2840,
    status: "active",
  },
  {
    id: "ds7",
    name: bi("Offline POS Data", "线下POS数据"),
    type: "manual",
    channel: "offline",
    lastSync: "2025-03-07 18:00",
    recordCount: 1200,
    status: "active",
  },
  {
    id: "ds8",
    name: bi("Customer Review Aggregator", "客户评价聚合"),
    type: "api",
    channel: "all",
    lastSync: "2025-03-09 03:00",
    recordCount: 12400,
    status: "error",
  },
];

export const mockImportHistory: ImportRecord[] = [
  { id: "imp1", sourceId: "ds1", sourceName: bi("Tmall Trade Data", "天猫交易数据"), fileName: "tmall_trades_w10.csv", status: "success", recordCount: 7200, errors: 0, importedAt: "2025-03-09 06:15" },
  { id: "imp2", sourceId: "ds2", sourceName: bi("Douyin E-commerce Data", "抖音电商数据"), fileName: "douyin_orders_w10.json", status: "success", recordCount: 6100, errors: 3, importedAt: "2025-03-09 06:12" },
  { id: "imp3", sourceId: "ds3", sourceName: bi("Xiaohongshu Content Metrics", "小红书内容数据"), fileName: "xhs_metrics_w10.csv", status: "success", recordCount: 2400, errors: 0, importedAt: "2025-03-09 06:10" },
  { id: "imp4", sourceId: "ds4", sourceName: bi("JD Sales Export", "京东销售导出"), fileName: "jd_sales_20250308.csv", status: "success", recordCount: 1800, errors: 0, importedAt: "2025-03-08 22:15" },
  { id: "imp5", sourceId: "ds5", sourceName: bi("Pinduoduo Order Data", "拼多多订单数据"), fileName: "pdd_orders_20250308.csv", status: "success", recordCount: 720, errors: 2, importedAt: "2025-03-08 18:20" },
  { id: "imp6", sourceId: "ds6", sourceName: bi("Ad Spend Tracker", "广告投放追踪"), fileName: "ad_spend_march_w2.xlsx", status: "success", recordCount: 340, errors: 0, importedAt: "2025-03-09 08:05" },
  { id: "imp7", sourceId: "ds8", sourceName: bi("Customer Review Aggregator", "客户评价聚合"), fileName: "reviews_sync_20250309.json", status: "failed", recordCount: 0, errors: 1, importedAt: "2025-03-09 03:15" },
  { id: "imp8", sourceId: "ds7", sourceName: bi("Offline POS Data", "线下POS数据"), fileName: "pos_march_w1.xlsx", status: "success", recordCount: 200, errors: 0, importedAt: "2025-03-07 18:30" },
  { id: "imp9", sourceId: "ds1", sourceName: bi("Tmall Trade Data", "天猫交易数据"), fileName: "tmall_trades_w09.csv", status: "success", recordCount: 7800, errors: 0, importedAt: "2025-03-02 06:15" },
  { id: "imp10", sourceId: "ds2", sourceName: bi("Douyin E-commerce Data", "抖音电商数据"), fileName: "douyin_orders_w09.json", status: "success", recordCount: 6500, errors: 1, importedAt: "2025-03-02 06:12" },
  { id: "imp11", sourceId: "ds1", sourceName: bi("Tmall Trade Data", "天猫交易数据"), fileName: "tmall_trades_w08.csv", status: "success", recordCount: 8200, errors: 0, importedAt: "2025-02-23 06:15" },
  { id: "imp12", sourceId: "ds2", sourceName: bi("Douyin E-commerce Data", "抖音电商数据"), fileName: "douyin_orders_w08.json", status: "success", recordCount: 7100, errors: 0, importedAt: "2025-02-23 06:12" },
];

export const mockFieldMappings: FieldMapping[] = [
  { sourceField: "order_id", targetField: "orderId", type: "string", sample: "TB20250309001234" },
  { sourceField: "order_time", targetField: "orderDate", type: "date", sample: "2025-03-09 14:23:00" },
  { sourceField: "item_title", targetField: "productName", type: "string", sample: "亮肤精华液 30ml" },
  { sourceField: "sku_code", targetField: "sku", type: "string", sample: "SKU001" },
  { sourceField: "pay_amount", targetField: "paymentAmount", type: "number", sample: "199.00" },
  { sourceField: "qty", targetField: "quantity", type: "number", sample: "2" },
  { sourceField: "refund_status", targetField: "refundStatus", type: "enum", sample: "none" },
  { sourceField: "buyer_nick", targetField: "customerId", type: "string", sample: "user_8a3f***" },
  { sourceField: "channel", targetField: "channel", type: "enum", sample: "tmall" },
  { sourceField: "ad_cost", targetField: "adSpend", type: "number", sample: "12.50" },
];
